// Generated by 'unplugin-auto-import'
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onMounted: typeof import('vue')['onMounted']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const stores: typeof import('./src/stores/index')['default']
  const useDrawer: typeof import('./src/stores/drawer')['useDrawer']
  const useLink: typeof import('vue-router')['useLink']
  const useLoginStore: typeof import('./src/stores/login')['useLoginStore']
  const useQuasar: typeof import('quasar')['useQuasar']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}
