// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/Address.vue')['default']
    Customer: typeof import('./src/components/Customer.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    GroupInfo: typeof import('./src/components/Group/Info.vue')['default']
    LayoutsDrawer: typeof import('./src/components/Layouts/Drawer.vue')['default']
    LayoutsExpansion: typeof import('./src/components/Layouts/Expansion.vue')['default']
    LayoutsItem: typeof import('./src/components/Layouts/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Todo: typeof import('./src/components/Todo.vue')['default']
    UserInfo: typeof import('./src/components/User/Info.vue')['default']
  }
}
